print("donner la note1")
note1=float(input())
print("donner la note2")
note2=float(input())
print("donner c1")
c1=float(input())
print("donner c2")
c2=float(input())
moyenne=(note1*c1+note2*c2)/(c1+c2)
print("la moyenne c'est =",moyenne)
